#mysql??????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #thymeleaf页面缓存开关，默认为ture开启缓存
    #建议在开发阶段关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
    #前缀(默认可以不写）
    prefix: classpath:/templates/
    #后缀(默认可以不写）
    suffix: .html


logging:
  level:
    com.example.springboot.mapper: debug


